[package]
name = "market"
version = "0.14.0"
authors = ["Justin Simerly <jsim2010@gmail.com>"]
description = "Infrastructure for producers and consumers"
license = "MIT"
repository = "https://github.com/jsim2010/market"
readme = "README.md"
keywords = ["producer", "consumer"]
categories = ["rust-patterns"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.4"
crossbeam-queue = "= 0.2"
fehler = "1.0"
log = "0.4"
never = "0.1"
thiserror = "1.0"
