[package]
name = "market_derive"
version = "0.1.0"
authors = ["Justin Simerly <jsim2010@gmail.com>"]
edition = "2018"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.7"
syn = "1.0.48"
