name: Partite
on:
  issue_comment:
    types: [created]

jobs:
  approve:
    if: ${{ endsWith(github.event.comment.body, '/approve') }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout project
      uses: actions/checkout@v2

    - name: create branch
      run: START="${{ github.event.issue.number }}-${{ github.event.issue.title }}" && BRANCH=${START// /_} && git switch -c ${BRANCH} && git push -u origin ${BRANCH}

    - name: update issue
      run: START="${{ github.event.issue.number }}-${{ github.event.issue.title }}" && BRANCH=${START// /_} && gh issue comment ${{ github.event.issue.number }} --body "Created branch '${BRANCH}'"
